create table if not exists public.events (
  id bigint generated by default as identity primary key,
  session_id text not null,
  event_name text not null check (
    event_name in ('page_view', 'cta_click', 'lead_submit', 'stay_duration')
  ),
  variant text default 'A',
  page text,
  duration_seconds integer,
  referrer text,
  user_agent text,
  created_at timestamptz default now()
);

create index if not exists events_created_at_idx on public.events (created_at desc);
create index if not exists events_event_name_idx on public.events (event_name);
create index if not exists events_session_id_idx on public.events (session_id);
create index if not exists events_variant_idx on public.events (variant);

alter table public.events enable row level security;
